// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostAuthCredentialParamsBody post auth credential params body
// swagger:model postAuthCredentialParamsBody
type PostAuthCredentialParamsBody struct {

	// access rules
	// Required: true
	AccessRules PostAuthCredentialParamsBodyAccessRules `json:"accessRules"`

	// redirection
	Redirection string `json:"redirection,omitempty"`
}

// Validate validates this post auth credential params body
func (m *PostAuthCredentialParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccessRules(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostAuthCredentialParamsBody) validateAccessRules(formats strfmt.Registry) error {

	if err := validate.Required("accessRules", "body", m.AccessRules); err != nil {
		return err
	}

	if err := m.AccessRules.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("accessRules")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostAuthCredentialParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostAuthCredentialParamsBody) UnmarshalBinary(b []byte) error {
	var res PostAuthCredentialParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
