// Code generated by go-swagger; DO NOT EDIT.

package domainswag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DomainRule Rule
// swagger:model domain.Rule
type DomainRule struct {

	// allowed values
	AllowedValues []string `json:"allowedValues"`

	// description
	Description string `json:"description,omitempty"`

	// fields
	Fields []string `json:"fields"`

	// inner configurations
	InnerConfigurations DomainRuleInnerConfigurations `json:"innerConfigurations"`

	// label
	Label string `json:"label,omitempty"`

	// required
	Required bool `json:"required,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this domain rule
func (m *DomainRule) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAllowedValues(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateFields(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DomainRule) validateAllowedValues(formats strfmt.Registry) error {

	if swag.IsZero(m.AllowedValues) { // not required
		return nil
	}

	return nil
}

func (m *DomainRule) validateFields(formats strfmt.Registry) error {

	if swag.IsZero(m.Fields) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DomainRule) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DomainRule) UnmarshalBinary(b []byte) error {
	var res DomainRule
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
