// Code generated by go-swagger; DO NOT EDIT.

package domainswag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DomainDataSmdLabel Representation of a protected label
// swagger:model domain.Data.SmdLabel
type DomainDataSmdLabel struct {

	// Label that is protected
	Label string `json:"label,omitempty"`

	// Trademark associated to the protected label
	Trademark string `json:"trademark,omitempty"`
}

// Validate validates this domain data smd label
func (m *DomainDataSmdLabel) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *DomainDataSmdLabel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DomainDataSmdLabel) UnmarshalBinary(b []byte) error {
	var res DomainDataSmdLabel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
