// Code generated by go-swagger; DO NOT EDIT.

package domainswag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DomainParentService Parent service
// swagger:model domain.ParentService
type DomainParentService struct {

	// Name of the parent service
	Name string `json:"name,omitempty"`

	// Type of the parent service
	Type string `json:"type,omitempty"`
}

// Validate validates this domain parent service
func (m *DomainParentService) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var domainParentServiceTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["/allDom"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		domainParentServiceTypeTypePropEnum = append(domainParentServiceTypeTypePropEnum, v)
	}
}

const (

	// DomainParentServiceTypeNrAllDom captures enum value "/allDom"
	DomainParentServiceTypeNrAllDom string = "/allDom"
)

// prop value enum
func (m *DomainParentService) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, domainParentServiceTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *DomainParentService) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DomainParentService) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DomainParentService) UnmarshalBinary(b []byte) error {
	var res DomainParentService
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
