// Code generated by go-swagger; DO NOT EDIT.

package domainswag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DomainDataProContact Representation of an .pro Contact Resource
// swagger:model domain.Data.ProContact
type DomainDataProContact struct {

	// Authority that certify your profesional status
	Authority string `json:"authority,omitempty"`

	// Website of the authority that certify your profesional status
	AuthorityWebsite string `json:"authorityWebsite,omitempty"`

	// .pro Contact ID
	ID int64 `json:"id,omitempty"`

	// Description of your job
	JobDescription string `json:"jobDescription,omitempty"`

	// License number given by the authority
	LicenseNumber string `json:"licenseNumber,omitempty"`
}

// Validate validates this domain data pro contact
func (m *DomainDataProContact) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *DomainDataProContact) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DomainDataProContact) UnmarshalBinary(b []byte) error {
	var res DomainDataProContact
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
