// Code generated by go-swagger; DO NOT EDIT.

package domainswag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostDomainZoneZoneNameImportParamsBody post domain zone zone name import params body
// swagger:model postDomainZoneZoneNameImportParamsBody
type PostDomainZoneZoneNameImportParamsBody struct {

	// zone file
	// Required: true
	ZoneFile *string `json:"zoneFile"`
}

// Validate validates this post domain zone zone name import params body
func (m *PostDomainZoneZoneNameImportParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateZoneFile(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostDomainZoneZoneNameImportParamsBody) validateZoneFile(formats strfmt.Registry) error {

	if err := validate.Required("zoneFile", "body", m.ZoneFile); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostDomainZoneZoneNameImportParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostDomainZoneZoneNameImportParamsBody) UnmarshalBinary(b []byte) error {
	var res PostDomainZoneZoneNameImportParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
