// Code generated by go-swagger; DO NOT EDIT.

package domainswag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostDomainServiceNameOwoParamsBody post domain service name owo params body
// swagger:model postDomainServiceNameOwoParamsBody
type PostDomainServiceNameOwoParamsBody struct {

	// fields
	// Required: true
	Fields []string `json:"fields"`
}

// Validate validates this post domain service name owo params body
func (m *PostDomainServiceNameOwoParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFields(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var postDomainServiceNameOwoParamsBodyFieldsItemsEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["address","email","phone"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postDomainServiceNameOwoParamsBodyFieldsItemsEnum = append(postDomainServiceNameOwoParamsBodyFieldsItemsEnum, v)
	}
}

func (m *PostDomainServiceNameOwoParamsBody) validateFieldsItemsEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, postDomainServiceNameOwoParamsBodyFieldsItemsEnum); err != nil {
		return err
	}
	return nil
}

func (m *PostDomainServiceNameOwoParamsBody) validateFields(formats strfmt.Registry) error {

	if err := validate.Required("fields", "body", m.Fields); err != nil {
		return err
	}

	for i := 0; i < len(m.Fields); i++ {

		// value enum
		if err := m.validateFieldsItemsEnum("fields"+"."+strconv.Itoa(i), "body", m.Fields[i]); err != nil {
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostDomainServiceNameOwoParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostDomainServiceNameOwoParamsBody) UnmarshalBinary(b []byte) error {
	var res PostDomainServiceNameOwoParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
