// Code generated by go-swagger; DO NOT EDIT.

package domainswag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostDomainServiceNameGlueRecordHostUpdateParamsBody post domain service name glue record host update params body
// swagger:model postDomainServiceNameGlueRecordHostUpdateParamsBody
type PostDomainServiceNameGlueRecordHostUpdateParamsBody struct {

	// ips
	// Required: true
	Ips []string `json:"ips"`
}

// Validate validates this post domain service name glue record host update params body
func (m *PostDomainServiceNameGlueRecordHostUpdateParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIps(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostDomainServiceNameGlueRecordHostUpdateParamsBody) validateIps(formats strfmt.Registry) error {

	if err := validate.Required("ips", "body", m.Ips); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostDomainServiceNameGlueRecordHostUpdateParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostDomainServiceNameGlueRecordHostUpdateParamsBody) UnmarshalBinary(b []byte) error {
	var res PostDomainServiceNameGlueRecordHostUpdateParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
