// Code generated by go-swagger; DO NOT EDIT.

package domainswag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostDomainZoneZoneNameDynHostLoginLoginChangePasswordParamsBody post domain zone zone name dyn host login login change password params body
// swagger:model postDomainZoneZoneNameDynHostLoginLoginChangePasswordParamsBody
type PostDomainZoneZoneNameDynHostLoginLoginChangePasswordParamsBody struct {

	// password
	// Required: true
	Password *strfmt.Password `json:"password"`
}

// Validate validates this post domain zone zone name dyn host login login change password params body
func (m *PostDomainZoneZoneNameDynHostLoginLoginChangePasswordParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePassword(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostDomainZoneZoneNameDynHostLoginLoginChangePasswordParamsBody) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	if err := validate.FormatOf("password", "body", "password", m.Password.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostDomainZoneZoneNameDynHostLoginLoginChangePasswordParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostDomainZoneZoneNameDynHostLoginLoginChangePasswordParamsBody) UnmarshalBinary(b []byte) error {
	var res PostDomainZoneZoneNameDynHostLoginLoginChangePasswordParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
