// Code generated by go-swagger; DO NOT EDIT.

package domainswag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostDomainServiceNameNameServerParamsBody post domain service name name server params body
// swagger:model postDomainServiceNameNameServerParamsBody
type PostDomainServiceNameNameServerParamsBody struct {

	// name server
	// Required: true
	NameServer PostDomainServiceNameNameServerParamsBodyNameServer `json:"nameServer"`
}

// Validate validates this post domain service name name server params body
func (m *PostDomainServiceNameNameServerParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNameServer(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostDomainServiceNameNameServerParamsBody) validateNameServer(formats strfmt.Registry) error {

	if err := validate.Required("nameServer", "body", m.NameServer); err != nil {
		return err
	}

	if err := m.NameServer.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("nameServer")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostDomainServiceNameNameServerParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostDomainServiceNameNameServerParamsBody) UnmarshalBinary(b []byte) error {
	var res PostDomainServiceNameNameServerParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
