// Code generated by go-swagger; DO NOT EDIT.

package domainswag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostDomainServiceNameDsRecordParamsBody post domain service name ds record params body
// swagger:model postDomainServiceNameDsRecordParamsBody
type PostDomainServiceNameDsRecordParamsBody struct {

	// keys
	// Required: true
	Keys PostDomainServiceNameDsRecordParamsBodyKeys `json:"keys"`
}

// Validate validates this post domain service name ds record params body
func (m *PostDomainServiceNameDsRecordParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKeys(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostDomainServiceNameDsRecordParamsBody) validateKeys(formats strfmt.Registry) error {

	if err := validate.Required("keys", "body", m.Keys); err != nil {
		return err
	}

	if err := m.Keys.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("keys")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostDomainServiceNameDsRecordParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostDomainServiceNameDsRecordParamsBody) UnmarshalBinary(b []byte) error {
	var res PostDomainServiceNameDsRecordParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
