// Code generated by go-swagger; DO NOT EDIT.

package domainswag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostDomainServiceNameUkOutgoingTransferParamsBody post domain service name uk outgoing transfer params body
// swagger:model postDomainServiceNameUkOutgoingTransferParamsBody
type PostDomainServiceNameUkOutgoingTransferParamsBody struct {

	// tag
	// Required: true
	Tag *string `json:"tag"`
}

// Validate validates this post domain service name uk outgoing transfer params body
func (m *PostDomainServiceNameUkOutgoingTransferParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTag(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostDomainServiceNameUkOutgoingTransferParamsBody) validateTag(formats strfmt.Registry) error {

	if err := validate.Required("tag", "body", m.Tag); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostDomainServiceNameUkOutgoingTransferParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostDomainServiceNameUkOutgoingTransferParamsBody) UnmarshalBinary(b []byte) error {
	var res PostDomainServiceNameUkOutgoingTransferParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
