// Code generated by go-swagger; DO NOT EDIT.

package domainswag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PostDomainZoneZoneNameChangeContactParamsBody post domain zone zone name change contact params body
// swagger:model postDomainZoneZoneNameChangeContactParamsBody
type PostDomainZoneZoneNameChangeContactParamsBody struct {

	// contact admin
	ContactAdmin string `json:"contactAdmin,omitempty"`

	// contact billing
	ContactBilling string `json:"contactBilling,omitempty"`

	// contact tech
	ContactTech string `json:"contactTech,omitempty"`
}

// Validate validates this post domain zone zone name change contact params body
func (m *PostDomainZoneZoneNameChangeContactParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PostDomainZoneZoneNameChangeContactParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostDomainZoneZoneNameChangeContactParamsBody) UnmarshalBinary(b []byte) error {
	var res PostDomainZoneZoneNameChangeContactParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
