// Code generated by go-swagger; DO NOT EDIT.

package domainswag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PostDomainServiceNameActivateZoneParamsBody post domain service name activate zone params body
// swagger:model postDomainServiceNameActivateZoneParamsBody
type PostDomainServiceNameActivateZoneParamsBody struct {

	// minimized
	Minimized *bool `json:"minimized,omitempty"`
}

// Validate validates this post domain service name activate zone params body
func (m *PostDomainServiceNameActivateZoneParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PostDomainServiceNameActivateZoneParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostDomainServiceNameActivateZoneParamsBody) UnmarshalBinary(b []byte) error {
	var res PostDomainServiceNameActivateZoneParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
