// Code generated by go-swagger; DO NOT EDIT.

package domainswag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PutDomainDataSmdSmdIDParamsBody put domain data smd smd Id params body
// swagger:model putDomainDataSmdSmdIdParamsBody
type PutDomainDataSmdSmdIDParamsBody struct {

	// data
	// Required: true
	Data *string `json:"data"`
}

// Validate validates this put domain data smd smd Id params body
func (m *PutDomainDataSmdSmdIDParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PutDomainDataSmdSmdIDParamsBody) validateData(formats strfmt.Registry) error {

	if err := validate.Required("data", "body", m.Data); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PutDomainDataSmdSmdIDParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PutDomainDataSmdSmdIDParamsBody) UnmarshalBinary(b []byte) error {
	var res PutDomainDataSmdSmdIDParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
