// Code generated by go-swagger; DO NOT EDIT.

package domainswag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ServiceRenewType Map a possible renew for a specific service
// swagger:model service.RenewType
type ServiceRenewType struct {

	// The service is automatically renewed
	Automatic bool `json:"automatic,omitempty"`

	// The service will be deleted at expiration
	DeleteAtExpiration bool `json:"deleteAtExpiration,omitempty"`

	// The service forced to be renewed
	Forced bool `json:"forced,omitempty"`

	// The service needs to be manually renewed and paid
	ManualPayment bool `json:"manualPayment,omitempty"`

	// period of renew in month
	Period int64 `json:"period,omitempty"`
}

// Validate validates this service renew type
func (m *ServiceRenewType) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceRenewType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceRenewType) UnmarshalBinary(b []byte) error {
	var res ServiceRenewType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
